# Generated by Django 5.2.5 on 2025-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "primary_muscle",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("legs", "Legs"),
                            ("arms", "Arms"),
                            ("shoulders", "Shoulders"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "secondary_muscles",
                    models.CharField(
                        choices=[
                            ("chest", "Chest"),
                            ("back", "Back"),
                            ("legs", "Legs"),
                            ("arms", "Arms"),
                            ("shoulders", "Shoulders"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "equipment",
                    models.CharField(
                        choices=[
                            ("dumbbell", "Dumbbell"),
                            ("barbell", "Barbell"),
                            ("kettlebell", "Kettlebell"),
                            ("bodyweight", "Bodyweight"),
                            ("machine", "Machine"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        max_length=100,
                    ),
                ),
                ("is_bodyweight", models.BooleanField(default=False)),
                ("video_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
