# Generated by Django 5.2.5 on 2025-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fitness", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="secondary_muscles",
            field=models.JSONField(
                blank=True, default=list, help_text="List of secondary muscles worked"
            ),
        ),
    ]
